### PR TITLE
🔧Fix building on windows environments

### PR DESCRIPTION
**Pull request by philltew**
This resolves the issue with running rollup on windows. Please ensure that it does not mess up on macOS environments.

### CODE REVIEW

**Comment by joostdecock** [comment]
Thank you for this. I don't have any Windows machine, so I'm flying blind here. But I do have some questions to understand the issue.

Essentially, this PR changes nothing. As in, it renames the config file, then updates the scripts in package.json with the new name. 

Which makes me assume that you did this because when running `rollup` it somehow tries to run the `rollup.js` file in the folder, rahter than `rollup` itself?

If that's the case, could you (or @woutervdub who also uses windows) please try running rollup globally:

```
npm install --global rollup
```

Because this fix would make the template different from every pattern out there, and I'd rather avoid that.

The [Rollup docs](https://rollupjs.org/guide/en) suggest installing it globally, so we might just need to add that step to the docs.

**Comment by philltew** [comment]
I have rollup installed globally but the problem remains. 

On windows when the `rollup` command is resolved windows will favour the one in the current directory. It then tries to open it, for me that means that the file opens in webstorm, for @pixieish it means that windows script host tries to run it, in either case the build fails. 

[Rollup docs](https://rollupjs.org/guide/en#configuration-files) recommend the config file be called `rollup.config.js` probably for this reason. 

I understand your reluctance to change a bunch of files but currently those files will not work in our environments. 

Additionally the PR removes the *spaces* in the `browserbuild` footer definition as this was also causing the command to fail.

**Comment by joostdecock** [comment]
Ok. Thanks for verifying this.

I'll merge this and adapt all other patterns accordingly.

**Comment by philltew** [comment]
Sweet, I hope there is more I can do for the project

**Comment by joostdecock** [comment]
Certainly. There's always a ton of stuff to do, so depending on your interests, I'm sure we can find something that would be fun to work at :)

**Comment by woutervdub** [comment]
Thanks!


Wouter van Wageningen

**Pull request merged**
